{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-cio/2.3.8/ktor-client-cio-2.3.8.module",
    "group": "io.ktor",
    "module": "ktor-client-cio",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-cio-jvm-2.3.8.jar",
          "url": "ktor-client-cio-jvm-2.3.8.jar",
          "size": 132268,
          "sha512": "88ab0e921084e3d66a8d893b2cce5e3eb27723abd0cf0fa2f8793cc0251c11ecc82085a49ff03a66fa8fc53b5f9680a26e18291168d3a19a24126fd4a7e31c75",
          "sha256": "7ad22d5e890bd478aa002b889de30c8281a855198d4906b66b8862531ac5898f",
          "sha1": "a34f1b10f1a92dae778e52d2683efe6aa8cda393",
          "md5": "c2138e93d5ce2381ac4b36ff983a5aad"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-cio-jvm-2.3.8.jar",
          "url": "ktor-client-cio-jvm-2.3.8.jar",
          "size": 132268,
          "sha512": "88ab0e921084e3d66a8d893b2cce5e3eb27723abd0cf0fa2f8793cc0251c11ecc82085a49ff03a66fa8fc53b5f9680a26e18291168d3a19a24126fd4a7e31c75",
          "sha256": "7ad22d5e890bd478aa002b889de30c8281a855198d4906b66b8862531ac5898f",
          "sha1": "a34f1b10f1a92dae778e52d2683efe6aa8cda393",
          "md5": "c2138e93d5ce2381ac4b36ff983a5aad"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-cio-jvm-2.3.8-sources.jar",
          "url": "ktor-client-cio-jvm-2.3.8-sources.jar",
          "size": 18738,
          "sha512": "cc9457f081d3b622128941edfe0a71feaa3c711b2c2755aefcbfcb3e3d932ab4c8f8a5b6a3fea823551a3156b3b8060e717f3374dbc562b193fa8107a666e155",
          "sha256": "f3ffcf0d8dbde4a26c02506562dd619e26d124ff720715c556a43bbbb2629549",
          "sha1": "87f60c4acd7762065c3891d46627f192a0320267",
          "md5": "489de7453237a3f5617a4eaf70809fd5"
        }
      ]
    }
  ]
}
